Update rtinst

diff --git a/scripts/rtinst b/scripts/rtinst
--- a/scripts/rtinst
+++ b/scripts/rtinst
@@ -770,21 +770,24 @@ sed -i "s/<user name>/$user/g" $home/.rtorrent.rc
 mkdir -p /var/www
 cd /var/www
 
-echo -n "RuTorrent: "; check_url $ru_url && echo "OK" || { echo "FAIL"; early_exit; }
+#echo -n "RuTorrent: "; check_url $ru_url && echo "OK" || { echo "FAIL"; early_exit; }
 
 if [ -d "/var/www/rutorrent" ]; then
   rm -r /var/www/rutorrent
 fi
 
-if [ $rudevflag = 1 ]; then
-   rurelease=$(git ls-remote -t https://github.com/Novik/ruTorrent v\* | cut -d/ -f3 | sort -V | tail -1)
-fi
+echo "Installing Rutorrent Version 3.8" | tee -a $logfile
+wget -q http://blazeshosting.com/scripts/rutorrent.zip | tee -a $logfile
+unzip rutorrent.zip
+rm -rf rutorrent.zip
 
-echo "Installing Rutorrent ($rurelease)" | tee -a $logfile
-wget -q https://github.com/Novik/ruTorrent/archive/$rurelease.tar.gz | tee -a $logfile
-tar -xzf $rurelease.tar.gz
-mv $(tar -tzf $rurelease.tar.gz | head -1) rutorrent
-rm $rurelease.tar.gz
+#echo "Installing Rutorrent ($rurelease)" | tee -a $logfile
+#wget -q https://github.com/Novik/ruTorrent/archive/$rurelease.tar.gz | tee -a $logfile
+#tar -xzf $rurelease.tar.gz
+#tar -xzf $rurelease.tar.gz
+#mv $(tar -tzf $rurelease.tar.gz | head -1) rutorrent
+#rm $rurelease.tar.gz
+
 
 echo "Configuring Rutorrent" | tee -a $logfile
 rm rutorrent/conf/config.php
